<<<<<<< HEAD
name: Deploy Jekyll site to Pages

on:
  # Trigger on pushes to the main branch
  push:
    branches: ["main"]

  # Allow manual trigger from Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Debug Bundler and Dependencies
        run: |
          echo "Bundler version:"
          bundle --version
          echo "Gems list:"
          gem list

      - name: Install Dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
=======
name: Deploy Jekyll site to Pages

on:
  # Trigger on pushes to the main branch
  push:
    branches: ["main"]

  # Allow manual trigger from Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Dependencies
        run: bundle install

      - name: Debug Environment
        run: |
          echo "Ruby version:"
          ruby --version
          echo "Bundler version:"
          bundle --version
          echo "Installed Gems:"
          gem list

      - name: Debug File System
        run: |
          echo "Current Directory:"
          pwd
          echo "List of Files:"
          ls -la
          echo "Content of _config.yml:"
          cat _config.yml

      - name: Debug Build Output
        run: |
          echo "Gemfile.lock content:"
          cat Gemfile.lock
          echo "Build Output:"
          bundle exec jekyll build --trace

      - name: Build Jekyll site
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
>>>>>>> 0c34969 (Fix dependencies and workflow)
